---

- name: Install and Start the Nginx
  hosts: all

  tasks:
  - name: Installing nginx
    yum:
      name: nginx
      state: present

  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: true
