---

- name: Test Product Lookup (Cartesian-like behavior)
  hosts: localhost
  gather_facts: no
  vars:
    list1:
      - a
      - b
    list2:
      - 1
      - 2
  tasks:
    - name: Cartesian combinations using product
      ansible.builtin.debug:
        msg: "Combination: {{ item.0 }} and {{ item.1 }}"
      loop: "{{ lookup('product', [list1, list2]) }}"

