---

- name: Working with tags
  hosts: all

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
    tags: install-nginx

  - name: Install httpd
    yum:
      name: httpd
      state: present
    tags: install-httpd
